---
name: 'bugroup-checks'
description: 'Aggregate several checks to a single one'
inputs:
  checks:
    description: 'A new-line separated list of RegExes matching the names of the checks to aggregate'
    required: true
  excludedChecks:
    description: 'A new-line separated list of RegExes to exclude from the aggregation'
    required: false
    default: ''
  self:
    description: 'The name of the job that runs this action'
    default: ''
    required: false
  requiredStatus:
    description: 'A new-line separated list of check status for which the aggregated check should be marked as successful'
    required: false
    default: |-
      skipped
      success
  githubToken:
    description: 'Github token of the repository (automatically created by Github)'
    default: ${{ github.token }}
    required: false
  ref:
    description: 'The ref to check'
    default: ${{ github.event.pull_request.head.sha }}
    required: false
  delay:
    description: 'The delay in seconds to wait for the checks to start running'
    default: '10'
    required: false
  interval:
    description: 'The interval in seconds to wait between checking again'
    default: '10'
    required: false
  jobIdentifier:
    description: 'The identifier of the check, which is used to identify the job from the rerun action'
    default: 'BUGROUP_CHECKS'
    required: false
outputs:
  allChecks:
    description: 'A JSON of checks returned by the last call to GitHubs listForRef'
  requiredChecks:
    description: 'A JSON of checks from allChecks that were required to be successful'
  unsuccessfulChecks:
    description: 'A JSON of checks from allChecks that have failed'
runs:
  using: 'node20'
  main: 'dist/index.js'
